spring:
  redis:
    host: 139.196.40.214
    port: 32315
    database: 1
    password: MJ.qwe689
    timeout: 0
    pool:
      max-active: 10000
      max-idle: 100
      max-wait: 500
      min-idle: 10


